services:

    simple-javascript-paycheck-calculator:

        container_name: simple-javascript-paycheck-calculator
        
        image: softwareshinobi/simple-javascript-paycheck-calculator

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "80:80"

